### ISSUE TITLE
Problem installing deb

### ISSUE THREAD

**Issue by mbonaci** [andypetrella/spark-notebook#144]
This is the result of the installation with `sudo dpkg -i` from the `install` folder on Ubuntu 14.04.1:

![image](https://cloud.githubusercontent.com/assets/497926/6992261/2f7570e2-dac4-11e4-9e45-ebe2fd66a5b8.png)

`sudo spark-notebook` output is at the bottom.

This is what happens if I try with Ubuntu Software Center:

![image](https://cloud.githubusercontent.com/assets/497926/6992114/38e87ba0-dabb-11e4-8fda-e949b2a86ce8.png)

I used zip in the end.

```sh
mbo@mbo-sia:~/install$ sudo spark-notebook
Play server process ID is 14850
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/spark-notebook/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/spark-notebook/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[DEBUG] [04/04/2015 11:15:30.253] [New I/O worker #1] [EventStream] StandardOutLogger started
[DEBUG] [04/04/2015 11:15:30.579] [New I/O worker #1] [EventStream(akka://NotebookServer)] logger log1-Slf4jLogger started
[DEBUG] [04/04/2015 11:15:30.582] [New I/O worker #1] [EventStream(akka://NotebookServer)] Default Loggers started
[error] a.a.OneForOneStrategy - ./conf/profiles (No such file or directory)
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:164) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
Caused by: java.io.FileNotFoundException: ./conf/profiles (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[na:1.7.0_75]
	at java.io.FileInputStream.<init>(FileInputStream.java:146) ~[na:1.7.0_75]
	at scala.io.Source$.fromFile(Source.scala:90) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.io.Source$.fromFile(Source.scala:75) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at notebook.server.NotebookClusters$.readFileAsJsonConf$1(NotebookClusters.scala:64) ~[noootsab.spark-notebook-0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0.jar:0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0]
[info] application - DASH → /
[error] application - 

! @6ll1kfmi2 - Internal server error, for (GET) [/clusters?_=1428138932020] ->

play.api.Application$$anon$1: Execution exception[[AskTimeoutException: Recipient[Actor[akka://NotebookServer/user/$a#-750934988]] had already been terminated.]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://NotebookServer/user/$a#-750934988]] had already been terminated.
	at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at controllers.Application$$anonfun$clusters$1.apply(Application.scala:190) ~[noootsab.spark-notebook-0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0.jar:0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0]
	at controllers.Application$$anonfun$clusters$1.apply(Application.scala:188) ~[noootsab.spark-notebook-0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0.jar:0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0]
	at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:481) ~[com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
[error] application - 

! @6ll1kfmhf - Internal server error, for (GET) [/profiles?_=1428138932018] ->

play.api.Application$$anon$1: Execution exception[[AskTimeoutException: Recipient[Actor[akka://NotebookServer/user/$a#-750934988]] had already been terminated.]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://NotebookServer/user/$a#-750934988]] had already been terminated.
	at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at controllers.Application$$anonfun$profiles$1.apply(Application.scala:183) ~[noootsab.spark-notebook-0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0.jar:0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0]
	at controllers.Application$$anonfun$profiles$1.apply(Application.scala:181) ~[noootsab.spark-notebook-0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0.jar:0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0]
	at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:481) ~[com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
[error] application - 

! @6ll1kfn49 - Internal server error, for (GET) [/api/contents/?type=directory&_=1428138932021] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.7.jar:2.3.7]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.SeqLike$class.size(SeqLike.scala:106) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:108) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69) ~[org.scala-lang.scala-library-2.10.4.jar:na]
```

**Comment by andypetrella** [comment]
mmmmh need to increase the quality so (but need first to know what that means :-D)

The other problem is a known one, but it's solved on master, the script has still to be launched from the "install" folder rather than the "bin" one :-/.

So, two things that should help you moving forward:
* use dpkg rather than the ubuntu center (yeah... I know)
* launch the script like that `./bin/spark-notebook`

As I said the second one is solved on master :-$
