### ISSUE TITLE
Error when adding a remote repo

### ISSUE THREAD

**Issue by gauravkumar37** [andypetrella/spark-notebook#160]
Hi,
While I am adding a remote repo with
`:remote-repo cloudera % default % https://repository.cloudera.com/artifactory/cloudera-repos/`
I am getting the following error:
`scala.MatchError: List(cloudera, default, https://repository.cloudera.com/artifactory/cloudera-repos/) (of class scala.collection.immutable.$colon$colon)
        at notebook.util.CustomResolvers$.fromString(Deps.scala:125)
        at notebook.client.ReplCalculator$$anonfun$10$$anon$1$$anonfun$receive$1.applyOrElse(ReplCalculator.scala:184)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at notebook.client.ReplCalculator$$anonfun$10$$anon$1.aroundReceive(ReplCalculator.scala:157)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
CustomResolvers#fromString → Cannot parse cloudera % default % https://repository.cloudera.com/artifactory/cloudera-repos/`
Please let me know if I am doing something wrong.

**Comment by andypetrella** [comment]
Argllllll SO SORRY!!!
Really need to update the doc here !!
We need now to specify the repo type actually, because in scala 2.10 SBT is used and it can manage more than maven repo (ivy)

So this is solved by adding this:

```
:remote-repo cloudera % default % https://repository.cloudera.com/artifactory/cloudera-repos %  maven
```

again, sorry :-(
