### ISSUE TITLE
Unwanted transitive dependency on Jackson 1.0.1

### ISSUE THREAD

**Issue by tmoerman** [andypetrella/spark-notebook#161]
(cfr. our Gitter conversation 22/04)

in a revision > v0.4.2 (commit fee5e29), spark notebook transitively depends on:
"org.codehaus.jackson" % "jackson-mapper-core" % "1.0.1"

This conflicts with ADAM/Avro, which expects a higher Jackson version.

```
val test_adam = "~/alignments/sim_reads_aligned.bam.adam"
> test_adam: String = ~/alignments/sim_reads_aligned.bam.adam

val rdd = ac.loadAlignments(test_adam)
> java.lang.NoSuchMethodError: org.codehaus.jackson.JsonFactory.enable(Lorg/codehaus/jackson/JsonParser$Feature;)Lorg/codehaus/jackson/JsonFactory;
	at org.apache.avro.Schema.<clinit>(Schema.java:86)
	at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:901)
	at org.apache.avro.specific.SpecificDatumReader.<init>(SpecificDatumReader.java:33)
	at org.bdgenomics.adam.serialization.AvroSerializer.<init>(ADAMKryoRegistrator.scala:39)
	at org.bdgenomics.adam.serialization.ADAMKryoRegistrator.registerClasses(ADAMKryoRegistrator.scala:69)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$4.apply(KryoSerializer.scala:98)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$4.apply(KryoSerializer.scala:98)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:98)
	at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:153)
	at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:115)
	at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:200)
	at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:101)
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:84)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:29)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:62)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1051)
	at org.apache.spark.rdd.NewHadoopRDD.<init>(NewHadoopRDD.scala:77)
	at org.apache.spark.SparkContext.newAPIHadoopFile(SparkContext.scala:848)
	at org.bdgenomics.adam.rdd.ADAMContext.adamLoad(ADAMContext.scala:163)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1$$anonfun$10.apply(ADAMContext.scala:494)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1$$anonfun$10.apply(ADAMContext.scala:491)
	at scala.Option.getOrElse(Option.scala:120)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1.apply(ADAMContext.scala:490)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadAlignments$1.apply(ADAMContext.scala:482)
	at org.apache.spark.rdd.Timer.time(Timer.scala:57)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAlignments(ADAMContext.scala:482)
```

Here's the ADAM file and a simple .snb illustrating the issue:
https://www.dropbox.com/sh/dxnmsh44ffnfzs6/AABiWuebz37lKVFSckXCdkVXa?dl=0

Hope this helps.
T

**Comment by andypetrella** [comment]
Ah I nailed it!
It's a transitive deps of hadoop 1.0.4 actually.
And ADAM is (AFAIK) okay starting with hadoop 2.2.0.

Hence, when using (on current master)
```
sbt -mem 8000 -Dhadoop.version=2.2.0
```

The load will work but the real read fails, here an example with count (`rdd.count`). This is not really an issue of the notebook I think but a parquet version or something I guess.

```
java.io.IOException: Could not read footer: java.lang.RuntimeException: file:/home/noootsab/data/genomics/sim_reads_aligned.bam.adam/part-r-00000.gz.parquet.crc is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [88, 94, 33, 60]
	at parquet.hadoop.ParquetFileReader.readAllFootersInParallel(ParquetFileReader.java:238)
	at parquet.hadoop.ParquetFileReader.readAllFootersInParallelUsingSummaryFiles(ParquetFileReader.java:179)
	at parquet.hadoop.ParquetInputFormat.getFooters(ParquetInputFormat.java:400)
	at parquet.hadoop.ParquetInputFormat.getFooters(ParquetInputFormat.java:372)
	at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:256)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1512)
```

Would it be okay to try this option?

Cheers,
andy

**Comment by andypetrella** [comment]
hello @tmoerman, do you still need some help on that one? I wonder if I should keep it open or what I was proposing sounded good :-D

**Comment by tmoerman** [comment]
Hi Andy, if it is not an issue of Spark-Notebook itself, you can close it.

I haven't yet been able to verify the fix (work pressure), if there's still a problem I'll let you know via Gitter or a new Github issue. Cheers.

**Comment by andypetrella** [comment]
Wooohooo awesome!
Thanks for confirming it :-D
