### ISSUE TITLE
NullPointerException when reading a file

### ISSUE THREAD

**Issue by rishihahs** [andypetrella/spark-notebook#210]
I downloaded spark-notebook and created a new notebook.

Then, when I executed: `sc.textFile("file:///path/to/file")`, I get a NullPointerException, of which the starting lines are:

This only happened after I used the `:cp` directive.

    java.lang.NullPointerException
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:79)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:29)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:62)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:945)
	at org.apache.spark.SparkContext.hadoopFile(SparkContext.scala:695)
	at org.apache.spark.SparkContext.textFile(SparkContext.scala:540)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:35)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:42)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:44)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:46)

**Comment by andypetrella** [comment]
hello @rishihahs sorry for the late :-(

I've just tested it on the branch-0.6 and it works AFAICT, can you tell me if the following test looks like yours?

thanks a lot

![cp-then-file](https://cloud.githubusercontent.com/assets/663344/8233918/3354189e-15d9-11e5-9d6b-0ac5eca72e1b.png)

**Comment by rishihahs** [comment]
Yes that looks like my test, and I was using 0.50.

However, I found that calling `reset()` fixes the problem.

**Comment by andypetrella** [comment]
ah oki :-D, 0.6.0 will fix that anyway though
