### ISSUE TITLE
On Windows, java.lang.IllegalArgumentException: Unknown under file system scheme C:\...

### ISSUE THREAD

**Issue by sourcedelica** [andypetrella/spark-notebook#220]
I'm getting an error starting spark-notebook on Windows.   

```
C:\dev\spark-notebook-0.5.2-scala-2.10.4-spark-1.3.1-hadoop-2.6.0\bin>spark-notebook                                                                
Play server process ID is 6568                                                                                                                      
SLF4J: Class path contains multiple SLF4J bindings.                                                                                                 
SLF4J: Found binding in [jar:file:/C:/dev/spark-notebook-0.5.2-scala-2.10.4-spark-1.3.1-hadoop-2.6.0/lib/ch.qos.logback.logback-classic-1.1.1.jar!/o
rg/slf4j/impl/StaticLoggerBinder.class]                                                                                                             
SLF4J: Found binding in [jar:file:/C:/dev/spark-notebook-0.5.2-scala-2.10.4-spark-1.3.1-hadoop-2.6.0/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf
4j/impl/StaticLoggerBinder.class]                                                                                                                   
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.                                                                    
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]                                                          
[warn] application - Start local micro tachyon                                                                                                      
*******************************************                                                                                                         
********** STARTING TACHYON  **************                                                                                                         
*******************************************                                                                                                         
Oops, cannot start the server.                                                                                                                      
java.lang.IllegalArgumentException: Unknown under file system scheme C:\Users\epederso\AppData\Local\Temp\Tachyon6544454648670098220U1434485912557  
        at tachyon.util.CommonUtils.illegalArgumentException(CommonUtils.java:346)                                                                  
        at tachyon.UnderFileSystem.get(UnderFileSystem.java:73)                                                                                     
        at tachyon.UnderFileSystem.get(UnderFileSystem.java:54)                                                                                     
        at tachyon.master.LocalTachyonCluster.deleteDir(LocalTachyonCluster.java:138)                                                               
        at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:160)                                                                   
        at notebook.share.Tachyon$.start$lzycompute(Tachyon.scala:54)                                                                               
        at notebook.share.Tachyon$.start(Tachyon.scala:48)                                                                                          
        at Global$.onStart(Global.scala:10)                                                                                                         
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)                                                                                  
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)                                                              
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)                                                              
        at scala.collection.immutable.List.foreach(List.scala:318)                                                                                  
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)                                                                               
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)                                                                                      
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)                                                                                      
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)                                                                             
        at play.api.Play$.start(Play.scala:90)                                                                                                      
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)                                                                         
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)                                                                        
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)                                                                
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)                                                                
        at scala.Option.map(Option.scala:145)                                                                                                       
        at play.core.server.NettyServer$.main(NettyServer.scala:275)                                                                           
        at play.core.server.NettyServer.main(NettyServer.scala)                                                                               ```

**Comment by andypetrella** [comment]
damned it looks like its a bug in tachyon :-/
https://github.com/amplab/tachyon/blob/v0.5.0/core/src/test/java/tachyon/master/LocalTachyonCluster.java#L154

Doesn't create a URL I think (like starting with `file://`)

So I guess best is to allow to not start tachyon, so on windows will can use the notebook but without it.

@sourcedelica could give me a favor a try it using spark 1.4.0? It should use the last version of tachyon (0.6.4). I hope it'll resolve it
But of course, if you cannot use this version it won't be a long term solution... just a sanity check
thanks :smile:

**Comment by sourcedelica** [comment]
We're on Spark 1.3.1 but I'll try it out to see if it gets past the Tachyon
error.

On Tuesday, June 16, 2015, Andy Petrella <notifications@github.com> wrote:

> damned it looks like its a bug in tachyon :-/
>
> https://github.com/amplab/tachyon/blob/v0.5.0/core/src/test/java/tachyon/master/LocalTachyonCluster.java#L154
>
> Doesn't create a URL I think (like starting with file://)
>
> So I guess best is to allow to not start tachyon, so on windows will can
> use the notebook but without it.
>
> @sourcedelica <https://github.com/sourcedelica> could give me a favor a
> try it using spark 1.4.0? It should use the last version of tachyon
> (0.6.4). I hope it'll resolve it
> But of course, if you cannot use this version it won't be a long term
> solution... just a sanity check
> thanks [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/issues/220#issuecomment-112573563>
> .
>


-- 
Sent from Gmail Mobile

**Comment by sourcedelica** [comment]
No luck with the Spark 1.4 version.  Same error.

**Comment by andypetrella** [comment]
okay, so local tachyon is buggy with windows, I'll add a `manager.tachyon.enabled` conf key to not start tachyon upon request then
thanks for taking the time to test it.

**Comment by andypetrella** [comment]
there you go, you can now pull master or branch 0.6 and go to the `application.conf` file to disable tachyon setting `manager.tachyon.enabled` to false (or removing it...)

hth
