### ISSUE TITLE
Error in the new Ehanced Dataframe widget

### ISSUE THREAD

**Issue by jarutis** [andypetrella/spark-notebook#249]
I got the following error trying to use the new dataframe renderer.

``` 
Lost task 0.0 in stage 0.0 (TID 0, hz-bd-hdp32.vinted.net): java.lang.ClassNotFoundException: notebook.front.widgets.DataFrameView$$anonfun$3
	at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:66)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:69)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:95)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:58)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: notebook.front.widgets.DataFrameView$$anonfun$3
	at java.lang.ClassLoader.findClass(ClassLoader.java:531)
	at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:30)
	at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:64)
```

**Comment by andypetrella** [comment]
This is indeed a usual serialization problem :-(.
We'll track this bad boy!

**Comment by andypetrella** [comment]
Okay, so I played a bit in an EMR cluster (for #260) with DataFrame viewer. Indeed there are two main problems that I faced we need to discuss further with @EronWright : 

* the viewer is in `common` module and submits a job, thanks to the pleasant spark serialization, the closure `_.toArray` to be run on the workers is actually a classes that needs to be shipped hence, the jar needs to be added to the spark.jars. This is rather easy to do from the application.conf file for distros but not so easy when using the notebook from SBT... there is no jar to be added, just classes :sob: 
* `_.toArray` reads the whole partition in memory at once, but actually `_.take(10).toArray` does it too, because for **both** with relatively small datasets and few partitions (thus) converted to a scala type, I always have an OOM for this call. The only way to get rid of this OOM was to `repartition` first. Maybe shall we, for now on, use fake partition with a given size in the call that will slide over the data. It's sad because there not so much options besides `take` then `drop`, or the `RDD.iterator` :-/

TBD

**Comment by andypetrella** [comment]
snif

**Comment by EronWright** [comment]
@andypetrella sorry I didn't look at this earlier, I will be on gitter this evening to discuss.

**Comment by andypetrella** [comment]
that's fine dude, no worries.

I worked on that to switch to a kindo skip, drop to solve the OOM, that is to give a simpler control to the user than having to repartition the dataset.

However, the class not found is still there due to anonymous function :-/

**Comment by andypetrella** [comment]
Okay, found a **hack**, that sanitizes my brain's health.

Injecting the `commons.commons_2.1....jar` works using either

* `:cp`
* `spark.jars` in the metadata

Bloody closures...

The quickest option I find for now is to always inject this jar in the spark context, using a distro it's rather easy, the problem will be when using the `spark-notebook` from SBT :-/.

It's a price I'd pay for that, since the impact is limited to only automatic display.

However, there is branch I started some days ago that is (aslo) meant for this kind of problems, the `clean-cp` one that creates cleaner modules that could be deployed.

Having modules deployable, and image, a distro will contain a default maven/ivy repository that is always included in the look up path we'll can refer the jars directly from there using artifact defs.

So for, now I'll put it dirty in the `spark.jars` until we split the jars into more granular libraries (not shipping the whole #!)
