### ISSUE TITLE
Autosave is broken!

### ISSUE THREAD

**Issue by Norpadon** [andypetrella/spark-notebook#251]
I get this message every time I try to save my notebook.

```
**************************************

{
  "cells" : [ {
    "metadata" : { },
    "cell_type" : "markdown",
    "source" : "###Import java stuff"
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "import java.awt.image._\nimport java.net.URL\nimport javax.imageio.ImageIO",
    "execution_count" : 31,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "import java.awt.image._\nimport java.net.URL\nimport javax.imageio.ImageIO\n",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : ""
      },
      "metadata" : { },
      "execution_count" : 31,
      "time" : "384 milliseconds"
    } ]
  }, {
    "metadata" : { },
    "cell_type" : "markdown",
    "source" : "###Functions for image loading"
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "def loadImage(url: String) = {\n  ImageIO.read(new URL(url))\n}\n\ndef showImg(image: BufferedImage, format: String = \"png\") = {\n  val viewport = img(format,\n                     image.getWidth.toString + \"px\",\n                     image.getHeight.toString + \"px\")\n  viewport(image)\n  viewport\n}",
    "execution_count" : 32,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "loadImage: (url: String)java.awt.image.BufferedImage\nshowImg: (image: java.awt.image.BufferedImage, format: String)notebook.front.SingleConnectedWidget[java.awt.image.BufferedImage]{implicit val codec: notebook.Codec[play.api.libs.json.JsValue,java.awt.image.BufferedImage]; lazy val toHtml: scala.xml.Elem; def url(u: java.net.URL): Unit; def file(f: java.io.File): Unit}\n",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : ""
      },
      "metadata" : { },
      "execution_count" : 32,
      "time" : "572 milliseconds"
    } ]
  }, {
    "metadata" : { },
    "cell_type" : "markdown",
    "source" : "###Test"
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "val test = loadImage(\"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTeJJ-mGnJxqksK_P1E8b8yHBVRc4GHcqmjnKwvrYiKJWmZ3tdL\")\nshowImg(test)",
    "execution_count" : 33,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "test: java.awt.image.BufferedImage = BufferedImage@60e8648a: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@30660b2 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 246 height = 205 #numDataElements 3 dataOff[0] = 2\nres17: notebook.front.SingleConnectedWidget[java.awt.image.BufferedImage]{implicit val codec: notebook.Codec[play.api.libs.json.JsValue,java.awt.image.BufferedImage]; lazy val toHtml: scala.xml.Elem; def url(u: java.net.URL): Unit; def file(f: java.io.File): Unit} = <anon$3 widget>\n",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : "<p>\n      <img width=\"246px\" height=\"205px\" data-bind=\"attr:{src: value}\"/>\n        <script data-this=\"{&quot;valueId&quot;:&quot;anon75613b932e983faa3068782f0f8d8675&quot;}\" type=\"text/x-scoped-javascript\">/*<![CDATA[*/\nreq(\n['observable', 'knockout'],\nfunction (O, ko) {\n  ko.applyBindings({\n      value: O.makeObservable(valueId)\n    },\n    this\n  );\n});\n            /*]]>*/</script>\n      </p>"
      },
      "metadata" : { },
      "execution_count" : 33,
      "time" : "674 milliseconds"
    } ]
  }, {
    "metadata" : { },
    "cell_type" : "markdown",
    "source" : "###Auxiliary convertors"
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "type ImageRGB = Array[Array[Array[Double]]]\ntype Bitmap = Array[Array[Boolean]]\n\ndef image2array(img: BufferedImage) = {\n  val raster = img.getData\n  Array.tabulate(raster.getHeight, raster.getWidth, 3) { (row, column, band) =>\n    raster.getSampleDouble(column, row, band)\n  }\n}\n\ndef array2image(arr: ImageRGB) = {\n  val img = new BufferedImage(arr(0).length, arr.length, BufferedImage.TYPE_INT_RGB)\n  val raster = img.getRaster\n  for {\n    row <- 0 until arr.length\n    column <- 0 until arr(row).length\n  } {\n    raster.setPixel(column, row, arr(row)(column))\n  }\n  img\n}\n\ndef binarize(img: ImageRGB, treshold: Double = 50) = {\n  img map { _ map { _.sum / 3 < treshold } }\n}\n\ndef debinarize(img: Bitmap,\n               color: Array[Double] = Array(0, 0, 0),\n               background: Array[Double] = Array(255, 255, 255)) = {\n  img map { _ map { if (_) color else background } }\n}\n\ndef downscale[T](img: Array[Array[T]], width: Int, height: Int)\n                (implicit arg0: scala.reflect.ClassTag[T]) = {\n  def sampleWidth = img(0).length / width\n  def sampleHeight = img.length / height\n  \n  Array.tabulate(height, width) { (row, column) =>\n    img(row * sampleHeight)(column * sampleWidth)\n  }\n}\n\ndef show(img: BufferedImage) = showImg(img)\n\ndef show(img: ImageRGB) = showImg(array2image(img))\n\ndef show(img: Bitmap, treshold: Double = 50) = showImg(array2image(debinarize(img)))\n\ndef showMap(image: Bitmap, width: Int = 500, height: Int = 500) = {\n  val viewport = img(\"png\", width.toString + \"px\", height.toString + \"px\")\n  viewport(array2image(debinarize(image)))\n  viewport\n}",
    "execution_count" : 34,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "defined type alias ImageRGB\ndefined type alias Bitmap\nimage2array: (img: java.awt.image.BufferedImage)Array[Array[Array[Double]]]\narray2image: (arr: ImageRGB)java.awt.image.BufferedImage\nbinarize: (img: ImageRGB, treshold: Double)Array[Array[Boolean]]\ndebinarize: (img: Bitmap, color: Array[Double], background: Array[Double])Array[Array[Array[Double]]]\ndownscale: [T](img: Array[Array[T]], width: Int, height: Int)(implicit arg0: scala.reflect.ClassTag[T])Array[Array[T]]\nshow: (img: java.awt.image.BufferedImage)notebook.front.SingleConnectedWidget[java.awt.image.BufferedImage]{implicit val codec: notebook.Codec[play.api.libs.json.JsValue,java.awt.image.BufferedImage]; lazy val toHtml: scala.xml.Elem; def url(u: java.net.URL): Unit; def file(f: java.io.File): Unit} <and> (img: Array[Array[A...",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : ""
      },
      "metadata" : { },
      "execution_count" : 34,
      "time" : "542 milliseconds"
    } ]
  }, {
    "metadata" : { },
    "cell_type" : "markdown",
    "source" : "###Test"
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "val testRGB = image2array(test)\nval testBitmap = binarize(testRGB, 80)\nshow(testRGB)",
    "execution_count" : 35,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "testRGB: Array[Array[Array[Double]]] = Array(Array(Array(26.0, 81.0, 60.0), Array(26.0, 81.0, 60.0), Array(24.0, 82.0, 58.0), Array(25.0, 83.0, 59.0), Array(25.0, 83.0, 58.0), Array(25.0, 84.0, 56.0), Array(26.0, 85.0, 57.0), Array(26.0, 85.0, 53.0), Array(29.0, 84.0, 53.0), Array(31.0, 85.0, 51.0), Array(35.0, 84.0, 52.0), Array(38.0, 84.0, 48.0), Array(37.0, 81.0, 46.0), Array(35.0, 77.0, 41.0), Array(34.0, 71.0, 37.0), Array(32.0, 67.0, 35.0), Array(39.0, 68.0, 40.0), Array(41.0, 67.0, 42.0), Array(40.0, 66.0, 39.0), Array(40.0, 66.0, 39.0), Array(39.0, 65.0, 36.0), Array(39.0, 66.0, 35.0), Array(39.0, 66.0, 35.0), Array(39.0, 66.0, 31.0), Array(41.0, 68.0, 33.0), Array(41.0, 69.0, 29.0), Array(41.0, 69.0, 29.0), Array(40.0, 69.0, 25.0), Array(40.0, 69.0, 25.0), Array(39.0, 68.0, 22....",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : "<p>\n      <img width=\"246px\" height=\"205px\" data-bind=\"attr:{src: value}\"/>\n        <script data-this=\"{&quot;valueId&quot;:&quot;anon636cc1ae58c4cf0ffcf90d3491635c64&quot;}\" type=\"text/x-scoped-javascript\">/*<![CDATA[*/\nreq(\n['observable', 'knockout'],\nfunction (O, ko) {\n  ko.applyBindings({\n      value: O.makeObservable(valueId)\n    },\n    this\n  );\n});\n            /*]]>*/</script>\n      </p>"
      },
      "metadata" : { },
      "execution_count" : 35,
      "time" : "1 second 85 milliseconds"
    } ]
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "show(testBitmap)",
    "execution_count" : 36,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "res19: notebook.front.SingleConnectedWidget[java.awt.image.BufferedImage]{implicit val codec: notebook.Codec[play.api.libs.json.JsValue,java.awt.image.BufferedImage]; lazy val toHtml: scala.xml.Elem; def url(u: java.net.URL): Unit; def file(f: java.io.File): Unit} = <anon$3 widget>\n",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : "<p>\n      <img width=\"246px\" height=\"205px\" data-bind=\"attr:{src: value}\"/>\n        <script data-this=\"{&quot;valueId&quot;:&quot;anon051bc4e03ead4968e1db26e083164a0b&quot;}\" type=\"text/x-scoped-javascript\">/*<![CDATA[*/\nreq(\n['observable', 'knockout'],\nfunction (O, ko) {\n  ko.applyBindings({\n      value: O.makeObservable(valueId)\n    },\n    this\n  );\n});\n            /*]]>*/</script>\n      </p>"
      },
      "metadata" : { },
      "execution_count" : 36,
      "time" : "597 milliseconds"
    } ]
  }, {
    "metadata" : {
      "trusted" : true,
      "input_collapsed" : false,
      "collapsed" : false
    },
    "cell_type" : "code",
    "source" : "showMap(downscale(testBitmap, 50, 50))",
    "execution_count" : 39,
    "outputs" : [ {
      "output_type" : "stream",
      "text" : "res22: notebook.front.SingleConnectedWidget[java.awt.image.BufferedImage]{implicit val codec: notebook.Codec[play.api.libs.json.JsValue,java.awt.image.BufferedImage]; lazy val toHtml: scala.xml.Elem; def url(u: java.net.URL): Unit; def file(f: java.io.File): Unit} = <anon$3 widget>\n",
      "name" : "stdout"
    }, {
      "output_type" : "execute_result",
      "data" : {
        "text/html" : "<p>\n      <img width=\"500px\" height=\"500px\" data-bind=\"attr:{src: value}\"/>\n        <script data-this=\"{&quot;valueId&quot;:&quot;anon3b862ed8f9fda82b935ed11510f3c342&quot;}\" type=\"text/x-scoped-javascript\">/*<![CDATA[*/\nreq(\n['observable', 'knockout'],\nfunction (O, ko) {\n  ko.applyBindings({\n      value: O.makeObservable(valueId)\n    },\n    this\n  );\n});\n            /*]]>*/</script>\n      </p>"
      },
      "metadata" : { },
      "execution_count" : 39,
      "time" : "500 milliseconds"
    } ]
  }, {
    "metadata" : {
      "trusted" : true,
      "collapsed" : false,
      "input_collapsed" : false
    },
    "cell_type" : "code",
    "source" : "",
    "execution_count" : 38,
    "outputs" : [ {
      "output_type" : "error",
      "ename" : "Error",
      "traceback" : [ "Incomplete (hint: check the parenthesis)" ]
    } ]
  } ],
  "metadata" : {
    "name" : "Numbers1",
    "user_save_timestamp" : "1970-01-01T03:00:00.000Z",
    "auto_save_timestamp" : "1970-01-01T03:00:00.000Z",
    "language_info" : {
      "name" : "scala",
      "file_extension" : "scala",
      "codemirror_mode" : "text/x-scala"
    },
    "trusted" : true,
    "customLocalRepo" : null,
    "customRepos" : null,
    "customDeps" : null,
    "customImports" : null,
    "customSparkConf" : null,
    "kernelspec" : {
      "name" : "spark",
      "display_name" : "Scala [2.10.4] Spark [1.4.0] Hadoop [1.0.4] "
    }
  },
  "nbformat" : 4,
  "nbformat_minor" : 0
}
**************************************

[error] play - Cannot invoke the action, eventually got an error: scala.MatchError: error (of class java.lang.String)
[error] application - 

! @6mnidgi50 - Internal server error, for (PUT) [/api/contents/Numbers1.snb] ->

play.api.Application$$anon$1: Execution exception[[MatchError: error (of class java.lang.String)]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.7.jar:2.3.7]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
Caused by: scala.MatchError: error (of class java.lang.String)
	at notebook.NBSerializer$$anonfun$11.apply(NBSerializer.scala:54) ~[na:na]
	at notebook.NBSerializer$$anonfun$11.apply(NBSerializer.scala:52) ~[na:na]
	at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:105) ~[play-json_2.10-2.4.0-M1.jar:2.4.0-M1]
	at play.api.libs.json.Format$$anon$3.reads(Format.scala:63) ~[play-json_2.10-2.4.0-M1.jar:2.4.0-M1]
	at play.api.libs.json.Json$.fromJson(Json.scala:115) ~[play-json_2.10-2.4.0-M1.jar:2.4.0-M1]
```

**Comment by Norpadon** [comment]
Updated version says this:
```
[error] application - parse notebook
java.lang.RuntimeException: {"obj.cells[12].outputs[0].traceback":[{"msg":"error.expected.jsstring","args":[]}],"obj.cells[12].outputs[0].name":[{"msg":"error.path.missing","args":[]}],"obj.cells[12].outputs[0].prompt_number":[{"msg":"error.path.missing","args":[]}]}
	at notebook.NBSerializer$.fromJson(NBSerializer.scala:226) ~[classes/:na]
	at controllers.Application$$anonfun$saveNotebook$1.apply(Application.scala:461) [classes/:na]
	at controllers.Application$$anonfun$saveNotebook$1.apply(Application.scala:458) [classes/:na]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) [play_2.10-2.3.7.jar:2.3.7]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) [play_2.10-2.3.7.jar:2.3.7]
```

**Comment by andypetrella** [comment]
Indeed, that's a problem I just fixed this PM... if you want to get rid of it without switching to the master, remove 
```
{
    "metadata" : {
      "trusted" : true,
      "collapsed" : false,
      "input_collapsed" : false
    },
    "cell_type" : "code",
    "source" : "",
    "execution_count" : 38,
    "outputs" : [ {
      "output_type" : "error",
      "ename" : "Error",
      "traceback" : [ "Incomplete (hint: check the parenthesis)" ]
    } ]
  }
```

Or at least remove 
```
{
      "output_type" : "error",
      "ename" : "Error",
      "traceback" : [ "Incomplete (hint: check the parenthesis)" ]
    }
```

Which is creating this match problem rather silently :-(

**Comment by andypetrella** [comment]
hey @Norpadon, I didn't saw your second message!

Sorry about that, I pushed something on master that will corrects this json problem

HTH

**Comment by andypetrella** [comment]
After some testing, I'm (rather ^^) confident that this should work now.
If you still have some problems, just let me know.
Meanwhile, let me close this entry :-D
