### ISSUE TITLE
ClassNotFoundException: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter

### ISSUE THREAD

**Issue by lev112** [andypetrella/spark-notebook#258]
I've compiled the notebook with:
```sbt -Dspark.version=1.4.0 -Dhadoop.version=2.5.0-cdh5.2.0 -Dwith.hive=true clean dist```

And got the following error when in the spark UI:
```
Problem accessing /jobs/. Reason:
    Server Error
Caused by:
java.lang.NullPointerException
        at org.spark-project.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
        at org.spark-project.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.spark-project.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.spark-project.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.spark-project.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.spark-project.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.spark-project.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.spark-project.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.spark-project.jetty.server.Server.handle(Server.java:370)
        at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
        at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

```

Looking at the log, I found that the cause is:
```java.lang.ClassNotFoundException: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter ```

My guess that this package is missing because all of the spark dependencies in ```Dependencies.scala``` exclude all ``org.apache.hadoop``

My solution was to add the dependency
```
"org.apache.hadoop" % "hadoop-yarn-server-web-proxy" % v excludeAll(
    ExclusionRule("org.apache.commons", "commons-exec"),
    ExclusionRule("commons-codec", "commons-codec"),
    ExclusionRule("com.google.guava", "guava")
    )
```

And it solves the problem, but I'd like to hear what you guys think

**Comment by andypetrella** [comment]
mmmmmmh good catch @lev112 !

Indeed, I saw it and talked about it in the #256 I was thinking that adding the /etc/hadoop/lib or something would clear that, but maybe including it in the build can be a good/better solution!

Would you create a PR for that? :-P

Thanks a lot anyway

**Comment by lev112** [comment]
I'll give it a try

**Comment by andypetrella** [comment]
cool :-D
