### ISSUE TITLE
Null pointer exception when intializing s3 textFile

### ISSUE THREAD

**Issue by tmandry** [andypetrella/spark-notebook#272]
Trying to run this line:

`val events = sparkContext.textFile("s3n://<bucket-name>/mixpanel/utexas/monthly/*.json.gz")`

Where <bucket-name> is the name of my bucket. It's the first line in the notebook. This line works every night in production. Here's what I get.

```
[debug] application - Sending info to websockets List() in notebook.server.CalcWebSocketService$CalcActor$$anon$4@53416011
[debug] application - Sending info to websockets List() in notebook.server.CalcWebSocketService$CalcActor$$anon$4@53416011
[error] a.a.OneForOneStrategy - null
java.lang.NullPointerException: null
	at notebook.server.CalcWebSocketService$CalcActor$$anonfun$receive$1.applyOrElse(CalcWebSocketService.scala:132) ~[noootsab.spark-notebook-0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-with-hive-with-parquet.jar:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-with-hive-with-parquet]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at notebook.server.CalcWebSocketService$CalcActor.aroundReceive(CalcWebSocketService.scala:37) ~[noootsab.spark-notebook-0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-with-hive-with-parquet.jar:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-with-hive-with-parquet]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [org.spark-project.akka.akka-actor_2.10-2.3.4-spark.jar:na]
[info] application - SAVE ? Untitled1.snb
```

**Comment by andypetrella** [comment]
mmmmh, looks like a web socket problem, could you try another kind a build maybe? a tar for instance, in case the docker has a problem with that -- but would surprise me

For S3 access, you exported the two AWS_ variables and adapted the sparkContext conf with the s3 credentials (including hadoopConfiguration) I guess right?

**Comment by tmandry** [comment]
You're right, I forgot to export the variables. I tried it in another Docker build (spark-notebook:0.5.2-scala-2.10.4-spark-1.4.0-hadoop-2.4.0) and it gave me an error message about it, but this error from the new version is unhelpful. Because of that I'll leave this issue open.

**Comment by andypetrella** [comment]
Indeed, and this NPE is actually thrown by Spark itself... with unhelpful message too :-/.

I knew that it was these var missing, because I had the problem once (I'm lying, so many times ^^).

Don't you have something else in the `logs/sn-session-...` log file? It would help to see how we can provide more relevant info at least in the notebook. Thanks
