### ISSUE TITLE
Docker image not working on Mac OSX (boot2docker)

### ISSUE THREAD

**Issue by hupiv** [andypetrella/spark-notebook#273]
Hi,

I generated an image using http://spark-notebook.io 

```
docker pull andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-cdh5.3.0-with-hive-with-parquet
 docker run -p 9000:9000 andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-cdh5.3.0-with-hive-with-parquet
```

But I have this error, when I launch on Mac Osx with boot2docker
```
~>docker run -it --rm -h sandbox -p 9000:9000 andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-cdh5.3.0-with-hive-with-parquet
Play server process ID is 1
Exception in thread "main" java.io.FileNotFoundException: /opt/docker/RUNNING_PID (Permission denied)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.(FileOutputStream.java:221)
at java.io.FileOutputStream.(FileOutputStream.java:171)
at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:233)
at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:221)
at scala.Option.map(Option.scala:145)
at play.core.server.NettyServer$.createServer(NettyServer.scala:221)
at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
at scala.Option.map(Option.scala:145)
at play.core.server.NettyServer$.main(NettyServer.scala:275)
at play.core.server.NettyServer.main(NettyServer.scala)
```

**Comment by andypetrella** [comment]
hello @hupiv, isn't there a copy paste problem ^^, because you didn't put the error report but the command a second time :-D

**Comment by hupiv** [comment]
I'm sorry :-(

~>docker run -it --rm  -h sandbox -p 9000:9000 andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-cdh5.3.0-with-hive-with-parquet
Play server process ID is 1
Exception in thread "main" java.io.FileNotFoundException: /opt/docker/RUNNING_PID (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:233)
	at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:221)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:221)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by andypetrella** [comment]
mmmmh, okay, I'll check the docker build -- looks like it has some problem.

While we fix this, you could use a tar or zip version maybe? Let me know if it's urgent (but will do asap of course)

**Comment by andypetrella** [comment]
_good_ news, I reproduced it, damned I'll fix that soon

**Comment by hupiv** [comment]
Thanks :-)

**Comment by andypetrella** [comment]
You can give it another try, it should be fixed now (still on 0.6.0 :-$)

**Comment by hupiv** [comment]
I generate on  http://spark-notebook.io the new package with the same options, and I have the same errors.
How I can help you ? with logs ?

**Comment by andypetrella** [comment]
Sorry I didn't saw your comment sooner... I noticed it myself :-(.
I should have fix this weird stuffs. Actually, the build work using the locally pushed docker images, but when push onto dockerhub and fetched on another machine → we got this problem. Really weirdo.

I solved it brute force by running the command using the docker's root... which in a sense doesn't really hurt and will allow easier folder mapping...

If you could retry, it'd be awesome. I did one try, it worked, but I don't trust myself at 4:30AM after having danced the push/pull/run dance beetween dockerhub, the spark-notebook.io node and my machine for 6 hours :-/.

thanks a lot ^^

**Comment by hupiv** [comment]
Hi,
now it seems the issue is coming from the docker repository, too many redirects when I try to pull the images

‘‘‘
~> docker pull andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.5.0-cdh5.3.0-with-hive-with-parquet
Pulling repository andypetrella/spark-notebook
FATA[0002] Get https://index.docker.io/v1/repositories/andypetrella/spark-notebook/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects 
‘‘‘

**Comment by hupiv** [comment]
I have a good news ! I change with another image and it works fine :-)): 
~> docker pull andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.3.0-hadoop-2.6.0-cdh5.4.0-with-hive-with-parquet

Thanks a lot for your help. About my previous message, do you want me to try again ?

**Comment by andypetrella** [comment]
of KoOl.
yeah, that would be super useful :-D
TiA

**Comment by andypetrella** [comment]
hello @hupiv I'm just wondering if I still need to keep this ticket opened :-D

any idea?

thanks
andy

**Comment by hupiv** [comment]
It's ok for me now. 

Thanks for your help.

**Comment by andypetrella** [comment]
cool, no problem :-D
thanks for all
