### ISSUE TITLE
Spark Notebook on Windows?

### ISSUE THREAD

**Issue by cbvoxel** [andypetrella/spark-notebook#281]
Hi! First off, I am sorry if I post my question in the wrong place! Let me know a better place then.

Short Story: I am having difficulties figuring out why the "kernel" is not starting. I have the logs of the "application", its stderr/stdout and the running application's logs (sn-...). Albeit "DEBUG" loglevel, I cannot see anything going wrong, yet the standalone (let alone yarn) won't work. On the (newly opened) notebook file it just stays at "initializing kernel". 

I downloaded the current version from here (git), and built it with sbt with Hadoop 2.7.0, spark 1.4.1 and with parquets on a windows 7 computer using intellij.

First off, I need to know if I am really getting all the logs. Please assist if there are more options.

Second, are there issues with spark-notebook regarding too long classpaths? In my case I'd say so. Looking into the logs of the "application" I can see a classpath being about 18000 characters long. I'm sure, spark-notebook is also using cmd. That would indeed break. I have changed code at

notebook.kernel.pfork.ForkableProcess at line 115

115 - val environment = System.getenv + ("CLASSPATH" -> (
116 -        sys.env.get("HADOOP_CONF_DIR").map(_ + ":").getOrElse("") +
117 -        sys.env.get("EXTRA_CLASSPATH").map(_ + ":").getOrElse("") 
118 - 		 + classPathString))

115 + val environment = System.getenv + ("CLASSPATH" -> (
116 +        sys.env.get("HADOOP_CONF_DIR").map(_ + ";").getOrElse("")
117 +        sys.env.get("EXTRA_CLASSPATH").map(_ + ";").getOrElse("") ))
118 +

And added needed Libs into EXTRA_CLASSPATH environment variable with the <libpath>/* notation (that should save a lot of characters, since the whole classpath only references spark-notebook's libs and the jre libs in ext). But I must admit that I don't really know what I am doing here (man it's just been a day). As it doesn't do the magic, I think I am at the wrong spot.

Maybe I am thinking too complicated and it's just my config. Either way, I would be extremely happy and grateful if some one would help!

**Comment by andypetrella** [comment]
Hello @cbvoxel, is probably the best place yes, or draw with gitter. 
I'm off until Friday, but I can try helping a bit. 
On Windows, you might have a problem indeed with the cp, maybe could you suggest a PR for your proposal then I'll take a look of you want. meanwhile you can also just hack the bin/spark-notebook to use lib/* :) 

for the log you should have everything, did you try just a cell with a 1+1? does it execute it? 

don't hesitate to post questions on gitter ^^

**Comment by cbvoxel** [comment]
I will see if 1+1 works, haven't tried! I do have another day to work on this issue, I am pretty confident that something useful will come out of this (hopefully leading to a PR suggestion as you mentioned). So catch ya later.

**Comment by andypetrella** [comment]
super cool, let me know, although I've little connectivity I'll try my best
to help you 😆

Le mer. 29 juil. 2015 22:47, cbvoxel <notifications@github.com> a écrit :

> I will see if 1+1 works, haven't tried! I do have another day to work on
> this issue, I am pretty confident that something useful will come out of
> this (hopefully leading to a PR suggestion as you mentioned). So catch ya
> later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/issues/281#issuecomment-126091490>
> .
>
-- 
andy

**Comment by cbvoxel** [comment]
Hi Andy,

okay granted that the length of the classpath and the ':' is something that is a problem when executing spark-notebook on windows, it seems to me that there is another problem, which I cannot figure out. It seems to be a Spark problem though. 

I have checked: 1+1 works, sparkContext doesn' exist. Indeed, on the stdout (not the logs though) I find the following message:

12:24:52.825 [Remote-akka.actor.default-dispatcher-2] ERROR notebook.client.ReplCalculator - Error in init script: 
java.lang.SecurityException: class "javax.servlet.ServletRegistration"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:952)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:666)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:136)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:129)
	at org.spark-project.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:98)
	at org.apache.spark.ui.JettyUtils$.createServletHandler(JettyUtils.scala:101)
	at org.apache.spark.ui.JettyUtils$.createServletHandler(JettyUtils.scala:92)
	at org.apache.spark.ui.WebUI.attachPage(WebUI.scala:78)
	at org.apache.spark.ui.WebUI$$anonfun$attachTab$1.apply(WebUI.scala:62)
	at org.apache.spark.ui.WebUI$$anonfun$attachTab$1.apply(WebUI.scala:62)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.ui.WebUI.attachTab(WebUI.scala:62)
	at org.apache.spark.ui.SparkUI.initialize(SparkUI.scala:50)
	at org.apache.spark.ui.SparkUI.<init>(SparkUI.scala:61)
	at org.apache.spark.ui.SparkUI$.create(SparkUI.scala:151)
	at org.apache.spark.ui.SparkUI$.createLiveUI(SparkUI.scala:106)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:300)
	at $iwC$$iwC$$anon$1.reset(<console>:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at $iwC$$iwC.<init>(<console>:83)
	at $iwC.<init>(<console>:106)
	at <init>(<console>:108)
	at .<init>(<console>:112)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1338)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
	at notebook.kernel.Repl$$anonfun$3.apply(Repl.scala:169)
	at notebook.kernel.Repl$$anonfun$3.apply(Repl.scala:169)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at scala.Console$.withOut(Console.scala:126)
	at notebook.kernel.Repl.evaluate(Repl.scala:168)
	at notebook.client.ReplCalculator.notebook$client$ReplCalculator$$eval$1(ReplCalculator.scala:388)
	at notebook.client.ReplCalculator$$anonfun$preStartLogic$2.apply(ReplCalculator.scala:403)
	at notebook.client.ReplCalculator$$anonfun$preStartLogic$2.apply(ReplCalculator.scala:401)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at notebook.client.ReplCalculator.preStartLogic(ReplCalculator.scala:401)
	at notebook.client.ReplCalculator.preStart(ReplCalculator.scala:408)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at notebook.client.ReplCalculator.aroundPreStart(ReplCalculator.scala:20)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Again, being all new to Spark that doesn't compute in my brain... maybe you can tell me something about it? Of course I would think I did something wrong during build, I used

> sbt -Dhadoop.version=2.7.0 -Dspark.version=1.3.1 -Dwith.parquet=true

and executed 'clean' and then 'dist'.

**Comment by cbvoxel** [comment]
Okay I got this now: I deleted all jars starting with javax. It seems to be conflicting with org.eclipse.jetty's javax classes...
I have a SparkContext now!

Let's see if that can be avoided.

Greets, Carsten

**Comment by andypetrella** [comment]
mmmmh good catches.
Let me try to recap :-D:

* we need to fix the windows path building pattern (separator)
* we need to fix the script generator (sbt native packager) to limit the classapth line (specially for Win)
* we need to figure out from where (again, 'coz I already had this problem actually, it just didn't popped out in my head) these javax libs are coming from (from hadoop 2.7.1?)

Do I miss something?

Besides that, good work man, very helpful and appreciated.

andy

**Comment by cbvoxel** [comment]
Yes, I am really glad to help! Great effort on your part with this project!

I finally figured out my very first problem (the one where it permanently says, initializing kernel). You won't believe it... although I didn't investigate further, but obviously IE 11 has a problem getting a notebook up and started. Might be that some obscure security setting is stopping it. Can't tell yet.

Other than that, you got all those points - none are missing!

cya, carsten

**Comment by cbvoxel** [comment]
So, I have come up with a small fix to these issues. Sorry, I am not familiar with working on opensource projects, so I will just copy the patch into this comment box... please guide me with a PR.

Index: modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala	(revision 8bd6b78d8aadf5984cf436cc2f161777d7b421ce)
+++ modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala	(revision )
@@ -7,6 +7,7 @@
 
 import com.typesafe.config.Config
 import org.apache.commons.exec._
+import org.apache.commons.exec.util.StringUtils
 import org.apache.log4j.PropertyConfigurator
 import org.slf4j.LoggerFactory
 import play.api.{Logger, Play}
@@ -61,8 +62,6 @@
 
   def classPath: IndexedSeq[String] = defaultClassPath
 
-  def classPathString = classPath.mkString(File.pathSeparator)
-
   def jvmArgs = {
     val builder = IndexedSeq.newBuilder[String]
 
@@ -110,12 +109,11 @@
 
     Future {
       log.info("Spawning %s".format(cmd.toString))
-
       // use environment because classpaths can be longer here than as a command line arg
-      val environment = System.getenv + ("CLASSPATH" -> (
-        sys.env.get("HADOOP_CONF_DIR").map(_ + ":").getOrElse("") +
-        sys.env.get("EXTRA_CLASSPATH").map(_ + ":").getOrElse("") +
-        classPathString))
+      val classpath = classPath ++ Array(
+        sys.env.get("HADOOP_CONF_DIR").getOrElse(""),
+        sys.env.get("EXTRA_CLASSPATH").getOrElse(""))
+      val environment = System.getenv + ("CLASSPATH" -> StringUtils.toString(classpath.toArray, File.pathSeparator))
       val exec = new KillableExecutor
 
       val completion = Promise[Int]()
@@ -126,6 +124,7 @@
         Logger.info(s"In working directory $workingDirectory")
 
         def onProcessFailed(e: ExecuteException) {
+          Logger.error(e.getMessage)
           e.printStackTrace()
         }
 
@@ -170,7 +169,7 @@
         } else {
           acc ++ (cl.asInstanceOf[URLClassLoader].getURLs map { u =>
             val f = new File(u.getFile)
-            URLDecoder.decode(f.getAbsolutePath, "UTF8")
+            URLDecoder.decode(f.getParent, "UTF8")
           })
         }
         urls(cl.getParent, us)
@@ -179,7 +178,8 @@
       }
     }
     val loader = Play.current.classloader
-    val gurls = urls(loader).distinct.filter(!_.contains("logback-classic")) //.filter(!_.contains("sbt/"))
+    val gurls = urls(loader).distinct.filter(!_.contains("logback-classic"))
+     .map(_ + "/*")//.filter(!_.contains("sbt/"))
     gurls
   }

**Comment by andypetrella** [comment]
Yop, I saw you PR, I see you got it in the right way! Thanks a lot!

I just left two comments as said there too, don't hesitate to get back to me,

cheers
