### ISSUE TITLE
`:cp` command takes 10s of minutes with not output, fails with mysterious error

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#298]
![](http://cl.ly/image/1z1r1e193i0D/Screen%20Shot%202015-08-18%20at%201.17.04%20AM.png)

That JAR exists and I've successfully added it to the classpath in YARN-backed notebooks like the one where I see the error above; I don't know why it took so long, why it ultimately failed, or why `sc` was no longer in scope afterward.

**Comment by ryan-williams** [comment]
All my ~100 executors seemed to be failing to communicate with the driver in the above app; they all had stack traces like:

```
15/08/18 00:16:07 INFO util.Utils: Successfully started service 'driverPropsFetcher' on port 58410.
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1643)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:65)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:146)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:245)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:107)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:97)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:159)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:66)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:65)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        ... 4 more
```

I have no idea why that would happen; I regularly run Spark apps via `{adam,spark}-{submit,shell}` on this YARN cluster with the same config params with no issues.

To try to simplify the repro case, I started an identical notebook with just 2 executors, and tried the same `:cp` command, and observed very different and equally puzzling failure modes:

![](http://cl.ly/image/3d3B0c022P2g/Screen%20Shot%202015-08-18%20at%201.38.09%20AM.png)

First, I ran a test job: `sc.parallelize(1 to 1000).count`. So far so good.

Then, I ran `:cp /hpc/users/willir31/application_1439224376754_3668/pageant-with-dependencies-1.0-SNAPSHOT.jar` again.

The first YARN app was shut down, a second one was started, and for whatever reason it re-ran the same test job as before. I don't know why that would be the intended behavior; I just wanted some classes added to my classpath.

When the automatic re-run of the test job finished, that YARN app was shut down, and a third one spun up, so any results from the second YARN app would presumably be destroyed.

Once the third YARN app, was ready, the notebook returned successfully from the `:cp` command, and `sc` is still in scope, unlike the time I documented at the start of this issue.

However, when I go to `import` classes from the JAR that I just `:cp`'d, they are not there (`org.hammerlab.…).

So again, it doesn't work, with a generous helping of strange behavior on the way. Please let me know if I am doing something wrong here.
