### ISSUE TITLE
Make spark-notebook work on the train

### ISSUE THREAD

**Issue by petervandenabeele** [andypetrella/spark-notebook#310]
I try to use spark-notebook on the train daily and each time I switch from home network Wifi to bluetooth over 3G (on Mac), I get errors like shown below this. I do not explicitly rely on external data and my browser just connects to 

```
http://localhost:9000/tree/core
http://localhost:9000/notebooks/core/Simple%20Spark.snb#
```
Is there a way to make this less dependent on the IP address the computer binds to and just use `localhost` ?

Thanks,

@petervandenabeele

```
[error]  - Failed to connect (27) to master /172.20.10.14:60210 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (28) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (28) to master /172.20.10.14:60210 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (29) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect to master /172.20.10.14:60203 after 29 attempts
java.io.IOException: Failed to connect to master /172.20.10.14:60203 after 29 attempts
	at tachyon.master.MasterClient.connect(MasterClient.java:220) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.worker_getPriorityDependencyList(MasterClient.java:773) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.getSortedPriorityDependencyList(WorkerStorage.java:127) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.run(WorkerStorage.java:150) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
Caused by: tachyon.org.apache.thrift.transport.TTransportException: java.net.SocketException: Network is unreachable
	at tachyon.org.apache.thrift.transport.TSocket.open(TSocket.java:185) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.connect(MasterClient.java:188) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.worker_getPriorityDependencyList(MasterClient.java:773) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.getSortedPriorityDependencyList(WorkerStorage.java:127) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
Caused by: java.net.SocketException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_51]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_51]
[error]  - Failed to connect (0) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (1) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (2) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (29) to master /172.20.10.14:60210 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect to master /172.20.10.14:60210 after 29 attempts
java.io.IOException: Failed to connect to master /172.20.10.14:60210 after 29 attempts
	at tachyon.master.MasterClient.connect(MasterClient.java:220) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.worker_getPriorityDependencyList(MasterClient.java:773) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.getSortedPriorityDependencyList(WorkerStorage.java:127) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.run(WorkerStorage.java:150) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
Caused by: tachyon.org.apache.thrift.transport.TTransportException: java.net.SocketException: Network is unreachable
	at tachyon.org.apache.thrift.transport.TSocket.open(TSocket.java:185) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.connect(MasterClient.java:188) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.master.MasterClient.worker_getPriorityDependencyList(MasterClient.java:773) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
	at tachyon.worker.WorkerStorage$CheckpointThread.getSortedPriorityDependencyList(WorkerStorage.java:127) ~[org.tachyonproject.tachyon-0.6.4.jar:na]
Caused by: java.net.SocketException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_51]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_51]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_51]
[error]  - Failed to connect (3) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable
[error]  - Failed to connect (4) to master /172.20.10.14:60203 : java.net.SocketException: Network is unreachable

```

**Comment by andypetrella** [comment]
heya,
this is sadly an unresolvable problem because comes from the in memory testing-only tachyon cluster, which is buggy because uses the back local ip lookup.
However, good news, you can simply launch the script or sbt by disabling it when you're disconnected.
```
./bin/spark-notebook -Dmanager.tachyon.enabled=false
```

or 

```
sbt -Dmanager.tachyon.enabled=false run
```

On master, using the latest spark version, 1.5.0-rc2, that needed a new version of tachyon, 0.7.1, I think it'll be solved (specially because now, I'm not hijacking tachyon tests jars to have this in-mem local mini-tachyon) .

**Comment by petervandenabeele** [comment]
I can confirm this works perfectly on the train

`./bin/spark-notebook -Dmanager.tachyon.enabled=false`

I did not try the newest version with tachyon yet.

**Comment by andypetrella** [comment]
Okido, anyway, I guess disabling tachyon while on train is not really an issue, or I would be interested in the use case ^^
