### ISSUE TITLE
Doecker on Mac does not work

### ISSUE THREAD

**Issue by dataanalyst** [andypetrella/spark-notebook#327]
Hello,

I used the docker image "0.6.1-scala-2.10.4-spark-1.5.0-hadoop-2.2.0" on Mac and it went through without any error, however, the web connection (localhost:9000) does not work and cannot connect to the server.

I ran
>>  docker run -p 9000:9000 andypetrella/spark-notebook:0.6.1-scala-2.10.4-spark-1.5.0-hadoop-2.2.0

I get: 
This webpage is not available
ERR_CONNECTION_REFUSED

Any idea as to what the problem could be? I have Java 1.8

Thanks,
E.

**Comment by andypetrella** [comment]
Hey @dataanalyst,

Indeed, I'm not a Mac user and I have overlooked that one. Using boot2docker or docker-machine, you're apparently stick with the IP of the virtual machine (which starts the docker actually)

Could you try then with this IP? Then we can flag this entry as documentation needed ^^

thanks a lot

and

**Comment by dataanalyst** [comment]
That solved the problem. Thanks!

**Comment by dataanalyst** [comment]
Hi, one more problem: I cannot get the IP address for Cassandra host. Checked the cassandraHost = "172.17.0.2", the IP that docker has ("192.168.99.100") and "192.168.99.101", all have the same problem and none finds the Cassandra host.

Any suggestion?

I am getting this error:


java.io.IOException: Failed to open native connection to Cassandra at {172.17.0.2}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:164)

**Comment by andypetrella** [comment]
Mmmmmh, and you have installed cassandra? In the same container?
It hasn't been told but indeed, cassandra is not installed hence the example needs to be adapted to access an available cassandra (in case I wasn't clear).

If not installed, so you could just try to setup it manually (a single node c* for brevity) and retry with it's IP (considering the cassandra docker is also an option of course-

**Comment by dataanalyst** [comment]
Aha! I thought that Cassandra comes with the container out of the box! 

Thanks for the clarification.

**Comment by andypetrella** [comment]
Yup, actually it isn't in the default docker, no problemo (it's not clear in the examples btw right?)

**Comment by smartinsightsfromdata** [comment]
Hi guys.  Apologies for jumping in.  I doubt that a single container can run spark and cassandra (unless some clever config with supervisord): dockers are meant to be for one purpose only.  But you can orchestrate cluster of them with compose etc..

Enzo
enzo@smartinsightsfromdata.com

**Comment by dataanalyst** [comment]
Thanks for the prompt response!
Sorry for sending more problems:

I started checking the spark-notebook container  on an Ubuntu server:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

I cannot run the container on the docker though.  I have OpenJDK on the system and I get this error.
Could it be the Java problem?
Thanks!

# sudo docker run -p 9000:9000 andypetrella/spark-notebook:0.6.1-scala-2.10.4-spark-1.5.0-hadoop-2.2.0
Play server process ID is 1
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/docker/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/docker/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (net.sf.ehcache.config.ConfigurationFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using default LocalFilesystemCluster for integration testing
Exception in thread "main" java.lang.NoSuchMethodError: tachyon.util.NetworkUtils.getPort(Lorg/apache/thrift/transport/TServerSocket;)I
	at tachyon.master.TachyonMaster.<init>(TachyonMaster.java:142)
	at tachyon.master.LocalTachyonMaster.<init>(LocalTachyonMaster.java:109)
	at tachyon.master.LocalTachyonMaster.create(LocalTachyonMaster.java:162)
	at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:189)
	at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:158)
	at notebook.share.Tachyon$.start$lzycompute(Tachyon.scala:60)
	at notebook.share.Tachyon$.start(Tachyon.scala:59)
	at Global$.onStart(Global.scala:11)
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by andypetrella** [comment]
@smartinsightsfromdata indeed, but for demo and for testing purpose I can (and I do ^^) have cassandra+kafka+spark+spark-notebook in a single docker. However, absolutely nor for prod, you're right

@dataanalyst mmmmh I think that Tachyon has still some problem with IP resolution for small local cluster. We can try disabling it (not sure docker will pass the arg though :cry:  ):
```
sudo docker run -p 9000:9000 andypetrella/spark-notebook:0.6.1-scala-2.10.4-spark-1.5.0-hadoop-2.2.0 -Dmanager.tachyon.enabled=false
```

**Comment by dataanalyst** [comment]
This one worked! thanks again!

**Comment by andypetrella** [comment]
awesome! but sorry for the pain :-(

**Comment by dataanalyst** [comment]
This level of customer service (especially unpaid) is unheard of! Thanks again!

**Comment by andypetrella** [comment]
hehe ^^
