### ISSUE TITLE
Windows java.lang.IllegalArgumentException: Unknown under file system scheme

### ISSUE THREAD

**Issue by rahulsh1** [andypetrella/spark-notebook#335]
Using Notebook `0.6.1` for Spark `1.4.1`, I set the config as given in https://github.com/andypetrella/spark-notebook/issues/220. My config

    tachyon {
    enabled = false #false if commented out / not present
    # url = "tachyon://example.com:18998"
    # baseDir = "/spark-storage-dir" # default to '/share'
    }

 I still get the following error on `Windows 7` with `Oracle JDK 1.8.0.45`. Even commenting out the `enabled` param didnt help.

    S:\Software\spark-notebook-0.6.1-scala-2.11.6-spark-1.4.1-hadoop-2.6.0\bin>spark-notebook.bat
		Play server process ID is 13620
		SLF4J: Class path contains multiple SLF4J bindings.
		SLF4J: Found binding in [jar:file:/S:/Software/spark-notebook-0.6.1-scala-2.11.6-spark-1.4.1-hadoop-2.6.0/lib/ch.qos.logback.logback-classic
		-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
		SLF4J: Found binding in [jar:file:/S:/Software/spark-notebook-0.6.1-scala-2.11.6-spark-1.4.1-hadoop-2.6.0/lib/org.slf4j.slf4j-log4j12-1.7.10
		.jar!/org/slf4j/impl/StaticLoggerBinder.class]
		SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
		SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
		[warn] application - Start local micro tachyon
		Oops, cannot start the server.
		java.lang.IllegalArgumentException: Unknown under file system scheme C:\Users\Ray\AppData\Local\Temp\Tachyon5202928292649088046U144419823
		2519
        at tachyon.UnderFileSystem.get(UnderFileSystem.java:76)
        at tachyon.UnderFileSystem.get(UnderFileSystem.java:57)
        at tachyon.master.LocalTachyonCluster.deleteDir(LocalTachyonCluster.java:128)
        at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:153)
        at notebook.share.Tachyon$.start$lzycompute(Tachyon.scala:53)
        at notebook.share.Tachyon$.start(Tachyon.scala:52)
        at Global$.onStart(Global.scala:11)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by andypetrella** [comment]
Arf weird.

You did changed the application.conf? If so, did you launched the binary by providing the path to it? like so:
```
./bin/spark-notebook -Dconfig.file=./conf/application.conf
```

If not, then this would be the problem, actually the changes weren't taken into account :-(.

On the other hand you can also try this way:
```
./bin/spark-notebook -Dmanager.tachyon.enabled=false
```

let me know if it works

cheers

**Comment by rahulsh1** [comment]
Thanks. That worked.

**Comment by adrian-git-hub-user** [comment]
If running from Windows : \spark-no
tebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.2.0\bin>spark-notebook.bat -Dconf
ig.file=../conf/application.conf

**Comment by andypetrella** [comment]
you're definitely right, this has been fixed on master actually.
good news you can get it from http://spark-notebook.io too :D

Le jeu. 5 nov. 2015 22:57, adrian-git-hub-user <notifications@github.com> a
écrit :

> If running from Windows : \spark-no
> tebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.2.0\bin>spark-notebook.bat
> -Dconf
> ig.file=../conf/application.conf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/issues/335#issuecomment-154207732>
> .
>
-- 
andy
