### ISSUE TITLE
can't run on windows

### ISSUE THREAD

**Issue by ittayd** [andypetrella/spark-notebook#352]
Using spark-notebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.7.1-with-hive
```
> .\spark-notebook.bat
Play server process ID is 4124
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/idror/Downloads/spark-notebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.7.1-with-hive/spark-notebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.7.1-with-hive/lib/ch.qos.logback.logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/idror/Downloads/spark-notebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.7.1-with-hive/spark-notebook-0.6.1-scala-2.11.6-spark-1.5.0-hadoop-2.7.1-with-hive/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[warn] application - Start local micro tachyon
Oops, cannot start the server.
java.lang.IllegalArgumentException: No Under File System Factory found for: C:\Users\idror\AppData\Local\Temp\Tachyon9005137488638350556U1445448775439
        at tachyon.underfs.UnderFileSystemRegistry.create(UnderFileSystemRegistry.java:109)
        at tachyon.underfs.UnderFileSystem.get(UnderFileSystem.java:99)
        at tachyon.underfs.UnderFileSystem.get(UnderFileSystem.java:83)
        at tachyon.master.LocalTachyonCluster.deleteDir(LocalTachyonCluster.java:139)
        at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:186)
        at tachyon.master.LocalTachyonCluster.start(LocalTachyonCluster.java:158)
        at notebook.share.Tachyon$.start$lzycompute(Tachyon.scala:60)
        at notebook.share.Tachyon$.start(Tachyon.scala:59)
        at Global$.onStart(Global.scala:11)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

**Comment by andypetrella** [comment]
indeed, tachyon has some quirks on win, you can easily get rid of that:

```
./bin/spark-notebook -Dmanager.tachyon.enabled=false
```

**Comment by ittayd** [comment]
```
bin> spark-notebook.bat -Dmanager.tachyon.enabled=false
Bad application path: false
```

**Comment by andypetrella** [comment]
mmmmh is that executable?

Would you use (instead)

```
bin\spark-notebook.bat -Dmanager.tachyon.enabled=false 
```

**Comment by ittayd** [comment]
I ran it exactly the same as when I got the exception. Changing outside of bin and running gives the same Bad application path error

**Comment by ittayd** [comment]
Need to use quotes:
```
> spark-notebook.bat '-Dmanager.tachyon.enabled=false'
```

**Comment by andypetrella** [comment]
ah crap sry about that!

but good catch! will remember next time!

Don't hesitate to come over on gitter as well: https://gitter.im/andypetrella/spark-notebook :-D
