### ISSUE TITLE
Error when trying to connect to a production cluster

### ISSUE THREAD

**Issue by jlcalbre** [andypetrella/spark-notebook#367]
I have the notebook set up and running on my edge node and everything works fine when I use setMaster("local").  But when I try use .setMaster("yarn-client") I get an error when trying to create the SparkContext.  The error I get is:

org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.

Looking at the logs, the stacktrace shows:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Logging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:597)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

Any ideas what is going on?  Happy to provide whatever additional info you need.

Thanks.

**Comment by andypetrella** [comment]
Heya, you should use the metadata to set this kind of conf. There are some info in the README if you like wrt cluster like yarn and mesos, I recommend you to have a quick look there.

BTW, here is the doc for the notebook metadata: https://github.com/andypetrella/spark-notebook/#spark-conf

hth

**Comment by huitseeker** [comment]
Just FYI : I've had this error happen to me with simply a spark-assembly jar built with Hadoop, for Hadoop-2.6, but running on Hadoop 2.2. Rebuilding for 2.2, shipping, and pointing to the correct spark-assembly fixed it.
