### ISSUE TITLE
NoClassDefFoundError when using code completion under Win10 x64

### ISSUE THREAD

**Issue by brakmic** [andypetrella/spark-notebook#369]
Hi,

I get this error when pressing TAB to autocomplete commands.

```shell
Uncaught error from thread [Remote-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Remote]
java.lang.NoClassDefFoundError: scala/tools/nsc/interpreter/jline/JLineDelimiter
        at notebook.kernel.Repl.argCompletor$lzycompute(Repl.scala:134)
        at notebook.kernel.Repl.argCompletor(Repl.scala:133)
        at notebook.kernel.Repl.complete(Repl.scala:275)
        at notebook.client.ReplCalculator$$anonfun$receive$2.applyOrElse(ReplCalculator.scala:473)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at notebook.client.ReplCalculator.aroundReceive(ReplCalculator.scala:26)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.interpreter.jline.JLineDelimiter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1073741824; support was removed in 8.0
[error] application - Process exited with an error: -1 (Exit value: -1)
org.apache.commons.exec.ExecuteException: Process exited with an error: -1 (Exit value: -1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:745)
```

I'm running SparkNotebook under Windows 10 x64 with following options/packages:

```code
Build: |  buildTime-Thu Oct 29 21:23:32 UTC 2015 | formattedShaVersion-0.6.2-SNAPSHOT-81e597df3397535977a855046e218b278e0ef434 | sbtVersion-0.13.8 | scalaVersion-2.11.6 | sparkNotebookVersion-0.6.2-SNAPSHOT | hadoopVersion-2.6.0 | jets3tVersion-0.7.1 | jlineDef-(jline,2.12) | sparkVersion-1.5.1 | withHive-true | withParquet-true |.
```

My **JDK** Version is 1.8.0_66

Regards,
Harris

**Comment by brakmic** [comment]
After some googling I found this info that seems to be related to the missing class path (JLine)

http://qnalist.com/questions/5488768/missing-jline-for-scala-2-11-0-rc1

It seems to have something to do with a private API. 

Citation:
```shell
> I know we haven't been very clear about this, but scala.tools is 
> internal API, so we offer no guarantees there. 
```

**Comment by andypetrella** [comment]
damn, does that appear all the time? You run a scala 2.10 notebook? or 2.11?

**Comment by brakmic** [comment]
Sadly, it appears all the time. I use scala 2.12.0-M3

**Comment by brakmic** [comment]
Sorry, the last comment was misleading. In the Spark-Notebook I use scala 2.11.6.

**Comment by andypetrella** [comment]
ah okay, it might be then indeed the version of (12 I think) used by the scala repl.

is this happening with scala 2.10?.

**Comment by brakmic** [comment]
Haven't tested it yet. I'll download another version of notebook with scala 2.10.

**Comment by brakmic** [comment]
I'm now waiting for the build of the following config:

```shell
notebook: master
scala: 2.10.4
spark: 1.5.1
hadoop: 2.6.0
with hive: true
with parquet: true
package: zip
```

**Comment by brakmic** [comment]
It works with the above configuration! :smile: 

![spark_notebook](https://cloud.githubusercontent.com/assets/56779/11015946/03305d22-8572-11e5-9da3-52c675b87562.png)
