### ISSUE TITLE
Exception when creating a notebook of the same name as an existing one

### ISSUE THREAD

**Issue by huitseeker** [andypetrella/spark-notebook#372]
```
! @6o3kddk1c - Internal server error, for (POST) [/api/contents/] ->

@6o3kddk1c: Execution exception in null:null
        at play.api.Application$class.handleError(Application.scala:296)
        at play.api.DefaultApplication.handleError(Application.scala:402)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320)
        at scala.Option.map(Option.scala:145)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: No copy_from
        at controllers.Application$.controllers$Application$$findkey$1(Application.scala:327)
        at controllers.Application$$anonfun$copyFrom$lzycompute$1$1.apply(Application.scala:341)
        at controllers.Application$$anonfun$copyFrom$lzycompute$1$1.apply(Application.scala:340)
        at scala.util.Success.flatMap(Try.scala:200)
        at controllers.Application$.copyFrom$lzycompute$1(Application.scala:340)
        at controllers.Application$.controllers$Application$$copyFrom$1(Application.scala:339)
        at controllers.Application$$anonfun$newNotebook$1.apply(Application.scala:345)
        at controllers.Application$$anonfun$newNotebook$1.apply(Application.scala:345)
        at scala.util.Try.orElse(Try.scala:82)
        at controllers.Application$.newNotebook(Application.scala:345)
        at controllers.Application$$anonfun$newContent$1$$anonfun$apply$26.apply(Application.scala:374)
        at controllers.Application$$anonfun$newContent$1$$anonfun$apply$26.apply(Application.scala:371)
        at scala.util.Success.flatMap(Try.scala:200)
        at controllers.Application$$anonfun$newContent$1.apply(Application.scala:371)
        at controllers.Application$$anonfun$newContent$1.apply(Application.scala:366)
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
        at play.api.mvc.Action$.invokeBlock(Action.scala:556)
        at play.api.mvc.Action$.invokeBlock(Action.scala:555)
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
        at scala.Option.map(Option.scala:145)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        ... 6 more
```

**Comment by andypetrella** [comment]
damn, good catch. Probably need to have a preflight check on the name...
