### ISSUE TITLE
can't build spark.version"="1.5.2" -D"hadoop.version"="2.6.0" -Dmesos.version="0.25.0"

### ISSUE THREAD

**Issue by vipmax** [andypetrella/spark-notebook#414]
djvip@DESKTOP-AFA4VEK C:\Users\djvip\spark-notebook                                   
> sbt -D"spark.version"="1.5.2" -D"hadoop.version"="2.6.0" -Dmesos.version="0.25.0"   
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support w
as removed in 8.0                                                                     
[info] Loading project definition from C:\Users\djvip\spark-notebook\project          
java.lang.ExceptionInInitializerError                                                 
        at Shared$$anonfun$sharedSettings$3.apply(Shared.scala:19)                    
        at Shared$$anonfun$sharedSettings$3.apply(Shared.scala:19)                    
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:604)                 
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.
scala:163)                                                                            
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.
scala:163)                                                                            
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)                  
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)                       
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$
mcV$sp(INode.scala:69)                                                                
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)            
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)                           
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)          
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)         
        at java.lang.Thread.run(Unknown Source)                                       
Caused by: java.lang.NullPointerException                                             
        at Dependencies$.<init>(Dependencies.scala:30)                                
        at Dependencies$.<clinit>(Dependencies.scala)                                 
        at Shared$$anonfun$sharedSettings$3.apply(Shared.scala:19)                    
        at Shared$$anonfun$sharedSettings$3.apply(Shared.scala:19)                    
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:604)                 
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.
scala:163)                                                                            
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.
scala:163)                                                                            
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)                  
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)                       
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$
mcV$sp(INode.scala:69)                                                                
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)            
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)                           
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)          
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)         
        at java.lang.Thread.run(Unknown Source)                                       
[error] java.lang.ExceptionInInitializerError                                         
[error] Use 'last' for the full log.                                                  
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?        

How can I use spark-notebook with spark"="1.5.2" "hadoop"="2.6.0" mesos "0.25.0? thanks for support!

**Comment by vidma** [comment]
@vipmax  sorry, my fault when refactoring (funny enough incremental `sbt run` worked).  will fix or revert soon ;)

@andypetrella could you please enable travis CI integration for pull requests. when I tried on my fork, travis builds were building, but failing. maybe I'd find some time to fix contious integration builds, so things like this would not happen.

**Comment by vidma** [comment]
@vipmax fixed.
