### ISSUE TITLE
Exception when cell returns a NaN value

### ISSUE THREAD

**Issue by Fija** [andypetrella/spark-notebook#520]
I have Double type column with `NaN` value, notebook shows error like this:

```
res105: Array[org.apache.spark.sql.Row] = Array([NaN], [NaN], [NaN], [NaN], [NaN])
Out[44]:
Ooops, exception in the cell: 
```

Console log looks like:
```
java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        ...
Caused by: java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:494)
        ...
```

**Comment by vidma** [comment]
so why not filter the crap out ?

**Comment by Fija** [comment]
I just show a simplified version. In real case there are other useful columns alongside, so if I filter them out I lose other valuable information

**Comment by vidma** [comment]
ok, seem to make sense.
btw which spark version did you use? so this happens when kinda `collecting`  `Array[Row]` as a return statement.

would this work fine at the end of cell:  `display(your_array)` ?

also will need to check if there's diffference between `null` and `NaN` values.
