### ISSUE TITLE
Executing spark while "play run" is failing

### ISSUE THREAD

**Issue by andypetrella** [andypetrella/spark-notebook#57]
This is a tricky one (again), because looks like it's only happening when running in Dev mode (like run).

Hence, it's still hard to debug or develop things involving spark execution thus (Spark, SparkInfo, Sql, and c°)... Which is sad.

So the symptom is that there is a mismatch while writing/reading `Tasks`  by the closure serializer (as far as the current investigation discovered). The problem occurs for `scala.Option`, `scala.None$`. The serialiazed (Java) is reporting bad serial uid, but the show ids (see below) are for Option and None.type → that's normal. Although, the written bytes should only refer the characters `None$` and never `Option`.

No idea, how this happens now, however, I guess that the `Option` field in `Task` is `metrics`.

```
[error] o.a.s.e.Executor - Exception in task 1.0 in stage 0.0 (TID 1)
java.io.InvalidClassException: scala.Option; local class incompatible: stream classdesc serialVersionUID = -2062608324514658839, local class serialVersionUID = 5081326844987135632
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617) ~[na:1.7.0_72]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622) ~[na:1.7.0_72]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_72]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622) ~[na:1.7.0_72]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_72]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_72]
[error] o.a.s.s.TaskSetManager - Task 7 in stage 0.0 failed 1 times; aborting job
```

**Comment by andypetrella** [comment]
Almost there, in https://github.com/andypetrella/spark-notebook/tree/remote-process-fix.

In this branch, I can work with spark when running play in dev mode. (The problem now is probably some config because akka always wants to listen on 2552 for all system it creates.)
