### ISSUE TITLE
Failed to initialize compiler: object scala.runtime in compiler mirror not found

### ISSUE THREAD

**Issue by antonkulaga** [andypetrella/spark-notebook#58]
I get "Failed to initialize compiler: object scala.runtime in compiler mirror not found" errors. 
What I did is just ran 
```scala
sbt run
```
And tried simplest example

**Comment by andypetrella** [comment]
Guyz just to add to the note here: I'm on the way to (apparently) solve this crap out, this is the branch: https://github.com/andypetrella/spark-notebook/tree/remote-process-fix.

I'm not far, just need to tune the akka conf to boot several system without conflicts

**Comment by andypetrella** [comment]
There we go, v0.1.3* on current master, allows spark to be used even when developing. 

Still have to deploy it now (s3 and docker)

**Comment by antonkulaga** [comment]
I git cloned from current master and started it with sbt and the bug is still there, here is my log after openning adam example:
```scala
SLF4J: Found binding in [jar:file:/home/antonkulaga/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/antonkulaga/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] [01/13/2015 11:42:50.249] [NotebookServer-akka.actor.default-dispatcher-6] [akka://NotebookServer/user/$b/$a] ReplCalculator preStart
 INIT SCRIPT 
<function0>

Failed to initialize compiler: object scala.runtime in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programatically, settings.usejavacp.value = true.

Failed to initialize compiler: object scala.runtime in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programatically, settings.usejavacp.value = true.
[ERROR] [01/13/2015 11:42:52.221] [NotebookServer-akka.actor.default-dispatcher-3] [akka://NotebookServer/user/$b/$a] assertion failed: null
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:218)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
	at akka.dispatch.Mailbox.run(Mailbox.scala:218)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.AssertionError: assertion failed: null
	at scala.Predef$.assert(Predef.scala:179)
	at org.apache.spark.repl.SparkIMain.initializeSynchronous(SparkIMain.scala:203)
	at org.apache.spark.repl.HackSparkILoop$$anonfun$process$1.apply$mcZ$sp(HackSparkILoop.scala:89)
	at org.apache.spark.repl.HackSparkILoop$$anonfun$process$1.apply(HackSparkILoop.scala:43)
	at org.apache.spark.repl.HackSparkILoop$$anonfun$process$1.apply(HackSparkILoop.scala:43)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.HackSparkILoop.process(HackSparkILoop.scala:43)
	at notebook.kernel.Repl.<init>(Repl.scala:121)
	at notebook.client.ReplCalculator$$anonfun$notebook$client$ReplCalculator$$repl$1.apply(ReplCalculator.scala:58)
	at notebook.client.ReplCalculator$$anonfun$notebook$client$ReplCalculator$$repl$1.apply(ReplCalculator.scala:57)
	at scala.Option.getOrElse(Option.scala:120)
	at notebook.client.ReplCalculator.notebook$client$ReplCalculator$$repl(ReplCalculator.scala:57)
	at notebook.client.ReplCalculator.notebook$client$ReplCalculator$$eval$1(ReplCalculator.scala:178)
	at notebook.client.ReplCalculator$$anonfun$preStartLogic$2.apply(ReplCalculator.scala:195)
	at notebook.client.ReplCalculator$$anonfun$preStartLogic$2.apply(ReplCalculator.scala:189)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at notebook.client.ReplCalculator.preStartLogic(ReplCalculator.scala:189)
	at notebook.client.ReplCalculator.preStart(ReplCalculator.scala:200)
	at akka.actor.ActorCell.create(ActorCell.scala:562)
	... 9 more
```

**Comment by andypetrella** [comment]
Mmmmh, let me check what happens with sbt... Although I'd be surprise if they behave differently.
Of course, you have no local changes right?
I'll get back soon.
Thanks for reporting!

**Comment by andypetrella** [comment]
Yop @antonkulaga, this is very strange. I cannot reproduce it. I'm trying with the Simple Spark example which should have the same error (in case of).
I tested on three different machine, including one that freshly cloned the master and run it using SBT :-/.

I poke you on hangout, so it'll be easier to discuss that (comments are too async ;))

**Comment by andypetrella** [comment]
Thanks @antonkulaga to figure that out. Looks like we can face this problem but "cleaning" the target `sbt clean` will resolve it.

However, it's rare, it'll occur when old (< 0.1.3) version of the notebook was built and classes are remaining in target.
