### ISSUE TITLE
ADD_JARS env var not loading the package

### ISSUE THREAD

**Issue by ibnesayeed** [andypetrella/spark-notebook#674]
I am using the Docker image `andypetrella/spark-notebook:0.6.3-scala-2.11.7-spark-1.6.1-hadoop-2.7.2` as my base image. after adding my code and other dependencies, I set the `ADD_JARS` env var.

```
ENV ADD_JARS=/path/to/warcbase-fatjar.jar
```

Then I run the `spark-notebook` command and access it from a browser. When I create a new notebook and execute the following code in it:

```
import org.warcbase.spark.matchbox._ 
```

I get the following error:

```
<console>:53: error: object warcbase is not a member of package org
       import org.warcbase.spark.matchbox._
                  ^
```

However, if I use `:cp /path/to/warcbase-fatjar.jar` before import then everything works well. I want to avoid that `:cp` call and I want this jar to be loaded for the entire session for all the notebooks. As a side not, `spark-shell` works with `ADD_JARS`, though it throws a deprecation warning.

**Comment by andypetrella** [comment]
Well, in the spark notebook ADD_JARS is a workaround to always include a deps in all notebooks' **executors**.
If you want to add it into the **driver** cp, hence you'll have to **also** use the `EXTRA_CLASSPATH` one

**Comment by ibnesayeed** [comment]
I tried doing that:

```
ENV ADD_JARS=/path/to/warcbase-fatjar.jar
ENV EXTRA_CLASSPATH=/path/to/warcbase-fatjar.jar
```

Which breaks the application.

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at play.api.Application$class.$init$(Application.scala:273)
	at play.api.DefaultApplication.<init>(Application.scala:406)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
```

I first thought that `EXTRA_CLASSPATH` might already be set with something which I am overwriting, but `ENV EXTRA_CLASSPATH=/path/to/warcbase-fatjar.jar:$EXTRA_CLASSPATH` didn't work either.

**Comment by ibnesayeed** [comment]
Can we have the `--jars` command line option like `spark-shell`?

**Comment by hblt-j** [comment]
I downloaded the docker version of the trial, increase the dependence on the emergence of suspended animation, what advice?
Here is more suitable to ask this question, I directly use: dp, the error is similar, like the context is ready to create can not be changed
  Quote question:
I downloaded the docker version of the trial, increase the dependence on the emergence of suspended animation, what advice?

**Comment by ibnesayeed** [comment]
Is there a directory where I can put my jar to get loaded automatically without explicitly adding it at run time?

**Comment by hblt-j** [comment]
First he just download jar package, followed by the need to restart, and if the local package is loaded, he should also set the context, added to the process to identify the directory, so understand it
Upstairs is a good way to do a depautoload action, download the package and add to the extension class path, but he should still have to restart

**Comment by hblt-j** [comment]
@andypetrella @antonkulaga @vidma Give the current solution and specific steps ，thanks

**Comment by hblt-j** [comment]
And I do not understand now: dp: sp: cp distinction

**Comment by anjackson** [comment]
@ibnesayeed I think the issue is the warcbase fatjar is bundling it's own version of Scala (2.10) and the system is borked by having two different Scala version on the classpath.

**Comment by ibnesayeed** [comment]
@anjackson, the only reason I was after this so that I can get rid of the `:cp /path/to/warcbase-fatjar.jar` line from the notebook file (in reference to: https://github.com/lintool/warcbase/issues/239). In my opinion it is an unnecessary detail that should be hidden from the user. Since it would a be a very specific purpose Docker image, an alternate approach could be to copy the fatjar in a place from where it is automatically loaded without explicitly telling (I am not sure how feasible it is though).

**Comment by anjackson** [comment]
@ibnesayeed however the JAR is loaded you'll get the same error because the warcbase JAR is not compatible with the version Scala spark-notebook is using. `EXTRA_CLASSPATH` works fine for me otherwise.

**Comment by ibnesayeed** [comment]
@anjackson, does that mean if we compile warcbase with the same version of Scala as packaged in the Spark Notebook, it would work?
