### ISSUE TITLE
#question/SOS: trouble connecting to h2o cluster

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [andypetrella/spark-notebook#722]
Hi Andy/contributors, 
I'm trying to load a h2o context in the notebook but everytime I try 

val hc = H2OContext.getOrCreate(sc)

I first get the error message

> java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.getUserJars(Lorg/apache/spark/SparkConf;Z)Lscala/collection/Seq;
  at org.apache.spark.repl.h2o.H2OInterpreter.createSettings(H2OInterpreter.scala:66)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.initializeInterpreter(BaseH2OInterpreter.scala:102)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.<init>(BaseH2OInterpreter.scala:293)
  at org.apache.spark.repl.h2o.H2OInterpreter.<init>(H2OInterpreter.scala:42)
  at water.api.scalaInt.ScalaCodeHandler.createInterpreterInPool(ScalaCodeHandler.scala:100)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:94)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:93)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at water.api.scalaInt.ScalaCodeHandler.initializeInterpreterPool(ScalaCodeHandler.scala:93)
  at water.api.scalaInt.ScalaCodeHandler.<init>(ScalaCodeHandler.scala:37)
  at water.api.CoreRestApi$.registerScalaIntEndp(RestAPIManager.scala:118)
  at water.api.CoreRestApi$.register(RestAPIManager.scala:58)
  at water.api.RestAPIManager.register(RestAPIManager.scala:46)
  at water.api.RestAPIManager.registerAll(RestAPIManager.scala:38)
  at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:114)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:97)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:267)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:281)
  ... 69 elided

then I get a null h2o cluster

> hc: org.apache.spark.h2o.H2OContext =

Sparkling Water Context:
 * H2O name: sparkling-water-alex.decastro_1345891740
 * cluster size: 0
 * list of used nodes:
  (executorId, host, port)
  ------------------------

  ------------------------

  Open H2O Flow in browser: http://null:0 (CMD + click in Mac OSX)

Here's the metadata of my notebook: 

> {
  "name": "sparkling-water test",
  "user_save_timestamp": "1970-01-01T01:00:00.000Z",
  "auto_save_timestamp": "1970-01-01T01:00:00.000Z",
  "language_info": {
    "name": "scala",
    "file_extension": "scala",
    "codemirror_mode": "text/x-scala"
  },
  "trusted": true,
  "customLocalRepo": null,
  "customRepos": null,
  "customDeps": [
    "ai.h2o % sparkling-water-core_2.11 % 2.0.0",
    "ai.h2o % sparkling-water-ml_2.11 % 2.0.0",
    "ai.h2o % sparkling-water-repl_2.11 % 2.0.0"
  ],
  "customImports": null,
  "customArgs": null,
  "customSparkConf": {
    "spark.app.name": "Notebook",
    "spark.master": "local[*]",
    "spark.executor.memory": "1G"
  },
  "kernelspec": {
    "name": "spark",
    "display_name": "Scala [2.11.8] Spark [2.0.0] Hadoop [2.2.0] {Hive ✓}"
  }
}

Any pointers are very welcome! I'm drowning here... 

Thanks
ALex

**Comment by alexDeCastroAtGit** [comment]
PS.: sparkling water works fine for me if I work via spark-shell

**Comment by andypetrella** [comment]
Hello @alexDeCastroAtGit would that be a clash in the spark versions used? Which versions of spark, spark-notebook and h2o are you using?

**Comment by alexDeCastroAtGit** [comment]
Hi Andy, thanks for the pointer. I'll check all around. I noticed my homebrew scala is 2.11 but sbt was calling an earlier version. h2o and spark are at their latest releases. Would the sbt console (scala) version make a difference? 

Like I said, somehow everything runs fine via shell. 

I'll drop you a line here again later. 

Cheers
Alex

**Comment by alexDeCastroAtGit** [comment]
Hi Andy, I've built spark-notebook from source (-b future-master) via SBT and NOW finally (after 3 hours) the damn thing is running. Awesome! It was likely a scala compatibility problem in my machine but the direct built worked fine (versus using the pre-built version). Go figure... 

Thanks
