### ISSUE TITLE
dependency hell

### ISSUE THREAD

**Issue by antonkulaga** [andypetrella/spark-notebook#802]
I have a dependency resolution problem form custion repositories.
```
ui-logs-1643> [Sat Jan 28 2017 17:21:06 GMT+0200 (EET)] [com.jcabi.aether.LogTransferListener] #transferFailed('GET FAILED http://repo.maven.apache.org/maven2/or..187../0.21.0/adam-parent-spark2_2.11-0.21.0.jar'): in 8.63µs
Kernel._handle_log_message @ kernel.js:978
i @ jquery.min.js:4
Kernel._handle_iopub_message @ kernel.js:1134
Kernel._finish_ws_message @ kernel.js:907
i @ jquery.min.js:4
deserialize @ /assets//ipython/services/kernels/serialize.js:60
Kernel._handle_ws_message @ kernel.js:898
i @ jquery.min.js:4
kernel.js:978 ui-logs-1644> [Sat Jan 28 2017 17:21:06 GMT+0200 (EET)] [com.jcabi.aether.Aether] #resolve(org.comp.bio.aging:adam-playground_2.11:jar:0.0.1, 'runtime', com.datafellas.utils.Deps$$anon$1@2a658d9d): thrown org.sonatype.aether.resolution.DependencyResolutionException(failed to load 'org.comp.bio.aging:adam-playground_2.11:jar:0.0.1 (runtime)' from ["main (http://dl.bintray.com/comp-bio-aging/main/, releases+snapshots) without authentication", "Maven2 local (file:/root/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/dcabdcbd-13b8-4ef9-a604-575aa321eb8b) out of com.jcabi.aether.Aether#fetch[237] in 18s
Kernel._handle_log_message @ kernel.js:978
i @ jquery.min.js:4
Kernel._handle_iopub_message @ kernel.js:1134
Kernel._finish_ws_message @ kernel.js:907
i @ jquery.min.js:4
deserialize @ /assets//ipython/services/kernels/serialize.js:60
Kernel._handle_ws_message @ kernel.js:898
i @ jquery.min.js:4
kernel.js:978 ui-logs-1645> [Sat Jan 28 2017 17:21:06 GMT+0200 (EET)] [Aether downloads] Failed to resolve dependencies: 
org.bdgenomics.adam %% adam-core-spark2 % 0.21.0
org.comp.bio.aging %% adam-playground % 0.0.1. Stacktrace:
org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'org.comp.bio.aging:adam-playground_2.11:jar:0.0.1 (runtime)' from ["main (http://dl.bintray.com/comp-bio-aging/main/, releases+snapshots) without authentication", "Maven2 local (file:/root/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/dcabdcbd-13b8-4ef9-a604-575aa321eb8b
	at com.jcabi.aether.Aether.fetch(Aether.java:237)
	at com.jcabi.aether.Aether.resolve_aroundBody2(Aether.java:180)
	at com.jcabi.aether.Aether$AjcClosure3.run(Aether.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.aether.Aether.resolve(Aether.java:177)
	at com.datafellas.utils.Deps$.resolve(Deps.scala:200)
	at com.datafellas.utils.Deps$$anonfun$20$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:227)
	at com.datafellas.utils.Deps$$anonfun$20$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:227)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datafellas.utils.Deps$$anonfun$20$$anonfun$apply$15.apply(Deps.scala:227)
	at com.datafellas.utils.Deps$$anonfun$20$$anonfun$apply$15.apply(Deps.scala:227)
	at scala.util.Success.flatMap(Try.scala:231)
	at com.datafellas.utils.Deps$$anonfun$20.apply(Deps.scala:227)
	at com.datafellas.utils.Deps$$anonfun$20.apply(Deps.scala:226)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at com.datafellas.utils.Deps$.script(Deps.scala:226)
	at notebook.client.ReplCalculator$$anonfun$9.apply(ReplCalculator.scala:96)
	at notebook.client.ReplCalculator$$anonfun$9.apply(ReplCalculator.scala:94)
	at scala.Option.map(Option.scala:146)
	at notebook.client.ReplCalculator.<init>(ReplCalculator.scala:94)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: failed to load 'org.comp.bio.aging:adam-playground_2.11:jar:0.0.1 (runtime)' from ["main (http://dl.bintray.com/comp-bio-aging/main/, releases+snapshots) without authentication", "Maven2 local (file:/root/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/dcabdcbd-13b8-4ef9-a604-575aa321eb8b
	... 45 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact org.bdgenomics.adam:adam-parent-spark2_2.11:jar:0.21.0 in main (http://dl.bintray.com/comp-bio-aging/main/)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at com.jcabi.aether.Aether.fetch(Aether.java:228)
	... 44 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.bdgenomics.adam:adam-parent-spark2_2.11:jar:0.21.0 in main (http://dl.bintray.com/comp-bio-aging/main/)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 45 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.bdgenomics.adam:adam-parent-spark2_2.11:jar:0.21.0 in main (http://dl.bintray.com/comp-bio-aging/main/)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$3.wrap(AsyncRepositoryConnector.java:1542)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$3.wrap(AsyncRepositoryConnector.java:1537)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector$GetTask.flush(AsyncRepositoryConnector.java:1035)
	at org.sonatype.aether.connector.async.AsyncRepositoryConnector.get(AsyncRepositoryConnector.java:409)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:457)
	... 47 more
```
I've tried many ways of writing the repo, including and not including "% maven" and "% ivy" parts. Nothing works. 
There is also a problem is that I do not see how I can fore-reload dependencies (when I restart the kernel it crashes)

**Comment by antonkulaga** [comment]
After republishing the lib and using shutdown after each time of notebook metadata editing I finally overcame this problem.
