### ISSUE TITLE
Case class causes exception java.util.NoSuchElementException: None.get 

### ISSUE THREAD

**Issue by yetsun** [andypetrella/spark-notebook#809]
I got the NoSuchElementException exception with the following code:
(My Spark version is 2.1.0. Scala version: 2.11.8. Hadoop version: 2.7.3)

```
case class MyClass(id: Int, name: String)

val myDF = sparkSession.sparkContext
.textFile("s3a://myS3Bucket/myTextFile.txt")
.map(_.split("\t"))
.map(_.map(_.trim))
.map(a => MyClass(a(0).toInt, a(1)))
.toDF
```

The exception only happened at the following line:
```
.map(a => MyClass(a(0).toInt, a(1)))
```
If I removed this line, there is no exception.

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 122, 10.210.208.233, executor 0): java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.apache.spark.storage.BlockInfoManager.releaseAllLocksForTask(BlockInfoManager.scala:343)
	at org.apache.spark.storage.BlockManager.releaseAllLocksForTask(BlockManager.scala:670)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The same code works fine in spark shell.

Thanks,
Jun

**Comment by vidma** [comment]
duplicated by https://github.com/andypetrella/spark-notebook/issues/807

I guess this is a Spark issue.
