### ISSUE TITLE
Error parsing a notebook

### ISSUE THREAD

**Issue by lucaventurini** [andypetrella/spark-notebook#97]
I have just fetched the master and tried to load a notebook written with the last `spark-notebook-0.2.0-spark-1.2.0-hadoop-2.4.0` online, but this wild error appears: (NB the examples work fine)

*An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.*

```java
[ERROR] parse notebook
java.lang.RuntimeException: {"obj.metadata.language_info.file_extension":[{"msg":"error.path.missing","args":[]}],"obj.metadata.language_info.codemirror_mode":[{"msg":"error.path.missing","args":[]}],"obj.metadata.language_info.name":[{"msg":"error.path.missing","args":[]}]}
	at notebook.NBSerializer$.fromJson(NBSerializer.scala:129)
	at controllers.Application$$anonfun$saveNotebook$1.apply(Application.scala:239)
	at controllers.Application$$anonfun$saveNotebook$1.apply(Application.scala:238)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] Cannot invoke the action, eventually got an error: java.lang.RuntimeException: {"obj.metadata.language_info.file_extension":[{"msg":"error.path.missing","args":[]}],"obj.metadata.language_info.codemirror_mode":[{"msg":"error.path.missing","args":[]}],"obj.metadata.language_info.name":[{"msg":"error.path.missing","args":[]}]}
[ERROR] 
```

**Comment by andypetrella** [comment]
Arf yes, my bad. In order to get highlighting back I needed to fix the notebook format.
The format generated by older version is not correct, however it's very simple to adapt since you only need to change 
```
"language_info" : "scala",
```
into

```
"language_info" : {
  "name" : "Scala",
  "file_extension" : "scala",
  "codemirror_mode" : "text/x-scala"
},
```
in the json file.

@see this [commit](https://github.com/andypetrella/spark-notebook/commit/108266d8a2e62200f12394fcfa799b05ebb4ea48#diff-f118b869c7c73b8e4535ed4d3dcc5e9b#diff-7) for deeper insights.

**Sorry about that!**

**Comment by lucaventurini** [comment]
Solved!
